AWSTemplateFormatVersion: 2010-09-09
Resources:
  CustomResourceEndpoint:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: Custom Resource Scaling API
      Description: API for Custom Resource Management. This is to be utilized by AWS AutoScaling.
      Body:
        swagger: "2.0"
        info:
          description: "Scaling API through API Gateway"
          version: "1.0.0"
          title: "Scaling API"
          license:
            name: MIT-0
            url: https://spdx.org/licenses/MIT-0.html
          basePath: "/v1"
          schemes:
           - "http"
          produces:
           - "application/json"
        paths:
          /scalableTargetDimensions/{scalableTargetDimensionId}:
            get:
              tags:
              - "ScalableTargets"
              summary: "Describe target"
              description: "The scalableTargetDimensions endpoint returns information about the registered \
             ScalableTargetDimension, including the desired and actual capacity."
              operationId: "controllers.default_controller.scalable_target_id_get"
              parameters:
              - name: "scalableTargetDimensionId"
                in: "path"
                description: "Id of ScalableTargetDimension to describe."
                required: true
                type: "string"
                format: ""
              responses:
                '200':
                  description: "JSON description of the ScalableTargetDimension"
                  schema:
                    '$ref': "#/definitions/ScalableTargetDimension"
                '400':
                  description: "Client Error"
                  schema:
                    '$ref': "#/definitions/Error"
                '403':
                  description: "Client Error: Not authorized"
                  schema:
                    '$ref': "#/definitions/Error"
                '404':
                  description: "Client Error: ScalableTargetDimension not found"
                  schema:
                    '$ref': "#/definitions/Error"
                '429':
                  description: "Client Error: Too Many Requests"
                  schema:
                    '$ref': "#/definitions/Error"
                '500':
                  description: "Server Error"
                  schema:
                    '$ref': "#/definitions/Error"
              x-tags:
              - tag: "ScalableTargets"
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                uri: !Ref IntegrationHttpEndpoint
                passthroughBehavior: "when_no_match"
                httpMethod: "GET"
                responses:
                  default:
                    statusCode: "500"
                  '200':
                    statusCode: "200"
                  '403':
                    statusCode: "403"
                  '404':
                    statusCode: "404"
                  '429':
                    statusCode: "429"
                  '4\d{2}':
                    statusCode: "400"
                requestParameters:
                  integration.request.path.scalableTargetDimensionId: "method.request.path.scalableTargetDimensionId"
                type: "http"
            patch:
              tags:
              - "ScalableTargets"
              summary: "Update ScalableTargetDimension"
              operationId: "controllers.default_controller.scalable_target_id_patch"
              consumes:
              - "application/json"
              parameters:
              - name: "scalableTargetDimensionId"
                in: "path"
                description: "Id of ScalableTargetDimension to update."
                required: true
                type: "string"
                format: ""
              - in: "body"
                name: "updateRequest"
                description: "The updateRequest contains a description of how the ScalableTargetDimension should be updated"
                required: true
                schema:
                  '$ref': "#/definitions/ScalableTargetDimensionUpdate"
              responses:
                '200':
                  description: "JSON description of ScalableTargetDimension"
                  schema:
                    '$ref': "#/definitions/ScalableTargetDimension"
                '400':
                  description: "Client Error"
                  schema:
                    '$ref': "#/definitions/Error"
                '403':
                  description: "Client Error: Not authorized"
                  schema:
                    '$ref': "#/definitions/Error"
                '404':
                  description: "Client Error: ScalableTargetDimension not found"
                  schema:
                    '$ref': "#/definitions/Error"
                '429':
                  description: "Client Error: Too Many Requests"
                  schema:
                    '$ref': "#/definitions/Error"
                '500':
                  description: "Server Error"
                  schema:
                    '$ref': "#/definitions/Error"
              x-tags:
              - tag: "ScalableTargets"
              security:
              - sigv4: []
              x-amazon-apigateway-integration:
                uri: !Ref IntegrationHttpEndpoint
                passthroughBehavior: "when_no_match"
                httpMethod: "PATCH"
                responses:
                  default:
                    statusCode: "500"
                  '200':
                    statusCode: "200"
                  '403':
                    statusCode: "403"
                  '404':
                    statusCode: "404"
                  '429':
                    statusCode: "429"
                  '4\d{2}':
                    statusCode: "400"
                requestParameters:
                  integration.request.path.scalableTargetDimensionId: "method.request.path.scalableTargetDimensionId"
                type: "http"
        securityDefinitions:
          sigv4:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "awsSigv4"
        definitions:
          Error:
            type: "object"
            properties:
              message:
                type: "string"
          ScalableTargetDimension:
            description: "A ScalableTargetDimension is a resource that represents the scaling state for a single dimension \
           of a scalable target"
            type: "object"
            required:
            - "actualCapacity"
            - "desiredCapacity"
            - "scalableTargetDimensionId"
            - "scalingStatus"
            - "version"
            properties:
              scalableTargetDimensionId:
                type: "string"
                format: ""
                description: "Unique identifier representing a specific ScalableTargetDimension."
              version:
                type: "string"
                format: ""
                description: "Version of the specific ScalableTargetDimension. It is useful in avoiding scaling action taken \
                on unregistered version of the ScalableTargetDimension"
              actualCapacity:
                type: "number"
                format: "double"
                description: "The actual capacity of the ScalableTargetDimension"
              desiredCapacity:
                type: "number"
                format: "double"
                description: "The desired capacity of the ScalableTargetDimension"
              scalingStatus:
                type: "string"
                format: ""
                description: "current status of scaling activity"
                enum:
                - "Pending" # scaling action has not yet begun
                - "InProgress" # scaling action is in progress
                - "Successful" # last scaling action was successful
                - "Failed" # last scaling action has failed
              resourceName:
                type: "string"
                format: ""
                description: "Optional user friendly name representing a specific Resource."
              dimensionName:
                type: "string"
                format: ""
                description: "Optional user friendly name representing a dimension of the resource to be scaled."
              failureReason:
                type: "string"
                format: ""
                description: "Optional failure reason that should be provided if the scaling action failed"
          ScalableTargetDimensionUpdate:
            description: "An update to be applied to the ScalableTargetDimension"
            type: "object"
            required:
            - "desiredCapacity"
            properties:
              desiredCapacity:
                type: "number"
                format: "double"
                description: "The new desired capacity of the target"
  PreProdStageDescription:
    DependsOn: PreProdClientCertificate
    Type: "AWS::ApiGateway::Stage"
    Properties:
      DeploymentId: !Ref PreProdDeployment
      Description: "Pre-prod stage"
      RestApiId: !Ref CustomResourceEndpoint
      StageName: "preprod"
      ClientCertificateId: !Ref PreProdClientCertificate
  ProdStageDescription:
    DependsOn: ProdClientCertificate
    Type: "AWS::ApiGateway::Stage"
    Properties:
      DeploymentId: !Ref ProdDeployment
      Description: "Prod stage"
      RestApiId: !Ref CustomResourceEndpoint
      StageName: "prod"
      ClientCertificateId: !Ref ProdClientCertificate
  PreProdClientCertificate:
    Type: "AWS::ApiGateway::ClientCertificate"
    Properties:
      Description: "Pre-prod client certificate"
  ProdClientCertificate:
    Type: "AWS::ApiGateway::ClientCertificate"
    Properties:
      Description: "Prod client certificate"
  PreProdDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      Description: "Pre-prod deployment for the scaling API that connects to an pre-prod integration endpoint"
      RestApiId: !Ref CustomResourceEndpoint
  ProdDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      Description: "Prod deployment for the scaling API that connects to an prod integration endpoint"
      RestApiId: !Ref CustomResourceEndpoint
Parameters:
  IntegrationHttpEndpoint:
    Type: String
    Description: Target service integration endpoint url
    Default: "http://127.0.0.1:8080/v1/scalableTargetDimensions/{scalableTargetDimensionId}"
    MinLength: 62    # http://a/scalableTargetDimensions/{scalableTargetDimensionId}
    MaxLength: 1600  # limit on length of resource id for Register API
    AllowedPattern: ^(https?:\/\/.*\/)scalableTargetDimensions\/\{scalableTargetDimensionId\}$
